import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nevbar from "./components/Nevbar"
import Footer from "./components/Footer"
import Add from "./components/Add"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  
       <Nevbar />

      <div className="flex flex-col md:flex-row bg-gray-100">
        <div className="md:w-3/4 px-4 bg-gray-100">
          {children}
        </div>
        <div className="md:w-1/4">
          <Add />
        </div>
      </div>
      
      <Footer/>

      </body>
    </html>
  );
}
